[server]
host = "0.0.0.0"
port = 3000

[database]
url = "mysql://root:root@localhost:3306/notes-sync"
max_connections = 10

[auth]
jwt_secret = "abcdefghfklmnopqrstuvwsyzshenjianzgmailcom789789"
jwt_expiration_days = 7

[redis]
url = "redis://localhost:6379"
# Redis 密码（可选）
# password = ""
